### ISSUE TITLE
InvalidOperationError when trying to run frida-discover

### ISSUE THREAD

**Issue by shadowslasher410** [termux/termux-root-packages#171]
So I got the following error when attempting to run frida-discover, and I dunno whether its a frida problem or a termux problem.
```
# frida-discover -p 9102
Attaching...                                               Injecting script...                                        
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida_tools/application.py", line 598, in _run
    work()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida_tools/application.py", line 313, in _try_start
    self._start()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida_tools/discoverer.py", line 35, in _start
    self._discoverer.start(self._session, self._runtime, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida_tools/discoverer.py", line 89, in start
    params = self._script.exports.start()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida/core.py", line 401, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida/core.py", line 333, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script is destroyed
```

**Comment by Grimler91** [comment]
I can reproduce it, but I also get it over adb, and with the frida-server from the github.com/frida/frida release page, so I don't think it is termux specific (leaving open until I know for sure)
